// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCms0TKzbDv-Gx_3lU_WMXFuNU5fe3Uku4',
    appId: '1:22413740184:web:ea3027d2a648841adee8ed',
    messagingSenderId: '22413740184',
    projectId: 'notes-e0f46',
    authDomain: 'notes-e0f46.firebaseapp.com',
    storageBucket: 'notes-e0f46.firebasestorage.app',
    measurementId: 'G-2ZJEYVHQXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgJZztMzWmQwZWbj2ED3ZI3LTr-2OZMJY',
    appId: '1:22413740184:android:a99df95c8e35e3e2dee8ed',
    messagingSenderId: '22413740184',
    projectId: 'notes-e0f46',
    storageBucket: 'notes-e0f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmy17cOI1R2VcrSxz6yHNuGru5oJTMlew',
    appId: '1:22413740184:ios:9da61af24ba0e11ddee8ed',
    messagingSenderId: '22413740184',
    projectId: 'notes-e0f46',
    storageBucket: 'notes-e0f46.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );

}